### ISSUE TITLE
Read Me File Update

### ISSUE THREAD

**Issue by g-umac** [FrankDaze/botpress_duplicate-finder_module#1]
Hi @FrankDaze   ,
unfortunately, the botpress modules does not have a duplicate finder. Can you please check

'https://github.com/botpress/botpress'

**Comment by FrankDaze** [comment]
did you follow this instructions? 

**Download the ready to use module**
Download the duplicate-finder.tgz file
In botpress open the modules page and click on the upload module button.
Select the duplicate-finder.tgz and upload it.
Now you should see the Duplicate Finder at the bottom of the page. Here you need to unzip it.
Activate the Duplicate Finder and restart your server.

**Comment by FrankDaze** [comment]
It's not included automatically in Botpress. It's a self made add-on-
